---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tokenginx
  namespace: tokenginx
  labels:
    app: tokenginx

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tokenginx
  namespace: tokenginx
  labels:
    app: tokenginx
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tokenginx
  namespace: tokenginx
  labels:
    app: tokenginx
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tokenginx
subjects:
- kind: ServiceAccount
  name: tokenginx
  namespace: tokenginx
